name = "portfolio-worker"
main = "src/index.js"
compatibility_date = "2026-07-21"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "3392397a-353c-43e2-bc95-43288526daf4"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "portfolio-arquivos"

[vars]
R2_PUBLIC_URL = "https://pub-2791ee9346c04bd99cfa979fbe8f5e9b.r2.dev"